= Entwicklerdokumentation v1

== Einführung und Ziele
=== Pizzaservice

Der Pizza-Service Papa Pizza liefert Pizzas und Getränke an seine Kunden auf telefonische +
Bestellung frei Haus. Da man bei Papa Pizza schlechte Erfahrungen mit "Telefonscherzen" +
gemacht hat, laufen die Bestellungen wie folgt:  	

* Neue Kunden tätigen ihre erste Bestellung persönlich in der Papa Pizza-Filiale. Dabei +
werden die Kundendaten nebst Telefonnummer aufgenommen. Mit der Rechnung +
erhält der Kunde seine erste TAN (Transaktionsnummer). 

* Im Regelfall bestellen Kunden telefonisch und weisen sich dabei mit ihrer +
Telefonnummer und TAN aus. Damit ist die TAN für den Kunden "verbraucht".

* Bei Auslieferung erhalten Kunden mit der Rechnung eine neue TAN.

* Wer seine Pizza persönlich abholt, erhält einen Rabatt von 10%.

Die Kunden können sich ihre Pizzas aus dem reichhaltigen Angebot an Zutaten individuell +
zusammenstellen. Getränke und Salate werden bei Papa Pizza natürlich ebenfalls angeboten. +
Bei einem Bestellwert von über 30 EUR erhält der Kunde ein Gratisgetränk. +
Pizzas werden in den verfügbaren Öfen im 5-Minuten-Takt gebacken, d.h. alle 5 Minuten +
kann eine weitere Pizza in einen der Öfen geschoben werden. Da die Anzahl der benötigten +
Öfen und Pizzabäcker vom Kundenandrang abhängt, wird sie vierteljährlich an die aktuellen +
Bestellungszahlen angepasst. +
Bei Annahme einer Bestellung wird diese zum nächstmöglichen Zeitpunkt eingeplant und +
dem Kunden der voraussichtliche Lieferzeitraum genannt. Die Lieferboten fahren +
viertelstündlich die Pizzas der vorangegangenen drei Back-Takte (natürlich in + 
Warmhaltebehältnissen) aus. +
Bei Bedarf wird eine Pizza gegen eine Kaution von 15 EUR mit der beliebten Papa Pizza- +
Essgarnitur (Becher, Riesenteller, Besteck) geliefert. Die Garnituren können innerhalb von +
vier Wochen in der Filiale oder beim Auslieferer zurückgegeben werden. Ansonsten verfällt +
die Kaution und gilt als Kaufpreis. +
Von Ihrer Software erwartet Papa Pizza eine angemessene Unterstützung aller Vorgänge +
einschließlich der Pflege des Kundenstamms (mit TAN-Verwaltung), des Personalstammes + 
und des laufenden Sortiments (dessen Zusammenstellung und Preise sich kontinuierlich +
ändern) sowie der wöchentlichen Abrechnungen der Filialen mit der Zentrale.

* Qualitätsziele

== Randbedingungen
* Hardware-Vorgaben
	** Server
	** Client-Geräte
* Software-Vorgaben
	** Java 1.8
	** Maven 2.6
	** Browser der HTML5 fähig ist
* Vorgaben zum Betrieb des Software
	** Applikation auf Server starten
	** Browser öffnen 
	** eigene Domain

== Kontextabgrenzung
* Externe Schnittstellen
	** Spring Salespoint Framework
	** ...


== Lösungsstrategie
Kurzer Überblick über Ihre grundlegenden Entscheidungen und Lösungsansätze, die jeder, der mit der Architektur zu tun hat, verstanden haben sollte.

== Bausteinsicht
* link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/artefacts/Entwurf/package__Package_Diagramm.jpg[Package-Diagramme]

== Entwurfsentscheidungen
* Architektur
* Verwendete Muster
	** MVC
	** Observer
	** Composite
	** Template-Methode
	** Objekt-Adapter
	** Singleton
* Persistenz
	** Daten-Initialisierer
* Benutzeroberfläche
	** HTML5 und CSS Seiten

[appendix]
== Glossar
