= Pflichtenheft

== Projektname

__Version:__    *1.0*

__Status:__     *In Arbeit*

__Stand:__      *29.10.2016*

== Zusammenfassung
Das Pflichtenheft enthält die Aufgabe und Wünsche des Kunden an die zu entwickelnde Software. 

== Inhaltsverzeichnis

== Aufgabenstellung und Zielsetzung

=== Pizzaservice

Der Pizza-Service Papa Pizza liefert Pizzas und Getränke an seine Kunden auf telefonische +
Bestellung frei Haus. Da man bei Papa Pizza schlechte Erfahrungen mit "Telefonscherzen" +
gemacht hat, laufen die Bestellungen wie folgt:  	

* Neue Kunden tätigen ihre erste Bestellung persönlich in der Papa Pizza-Filiale. Dabei +
werden die Kundendaten nebst Telefonnummer aufgenommen. Mit der Rechnung +
erhält der Kunde seine erste TAN (Transaktionsnummer). 

* Im Regelfall bestellen Kunden telefonisch und weisen sich dabei mit ihrer +
Telefonnummer und TAN aus. Damit ist die TAN für den Kunden "verbraucht".

* Bei Auslieferung erhalten Kunden mit der Rechnung eine neue TAN.

* Wer seine Pizza persönlich abholt, erhält einen Rabatt von 10%.

Die Kunden können sich ihre Pizzas aus dem reichhaltigen Angebot an Zutaten individuell +
zusammenstellen. Getränke und Salate werden bei Papa Pizza natürlich ebenfalls angeboten. +
Bei einem Bestellwert von über 30 EUR erhält der Kunde ein Gratisgetränk. +
Pizzas werden in den verfügbaren Öfen im 5-Minuten-Takt gebacken, d.h. alle 5 Minuten +
kann eine weitere Pizza in einen der Öfen geschoben werden. Da die Anzahl der benötigten +
Öfen und Pizzabäcker vom Kundenandrang abhängt, wird sie vierteljährlich an die aktuellen +
Bestellungszahlen angepasst. +
Bei Annahme einer Bestellung wird diese zum nächstmöglichen Zeitpunkt eingeplant und +
dem Kunden der voraussichtliche Lieferzeitraum genannt. Die Lieferboten fahren +
viertelstündlich die Pizzas der vorangegangenen drei Back-Takte (natürlich in + 
Warmhaltebehältnissen) aus. +
Bei Bedarf wird eine Pizza gegen eine Kaution von 15 EUR mit der beliebten Papa Pizza- +
Essgarnitur (Becher, Riesenteller, Besteck) geliefert. Die Garnituren können innerhalb von +
vier Wochen in der Filiale oder beim Auslieferer zurückgegeben werden. Ansonsten verfällt +
die Kaution und gilt als Kaufpreis. +
Von Ihrer Software erwartet Papa Pizza eine angemessene Unterstützung aller Vorgänge +
einschließlich der Pflege des Kundenstamms (mit TAN-Verwaltung), des Personalstammes + 
und des laufenden Sortiments (dessen Zusammenstellung und Preise sich kontinuierlich +
ändern) sowie der wöchentlichen Abrechnungen der Filialen mit der Zentrale. 

== Fachlicher Überblick
Einleitung für fachfremde Personen

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm

link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/artefacts/component__Kontextdiagramm.jpg[Kontextdiagramm]

=== Top-level architecture

link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/artefacts/component__Top_Level_Architektur.jpg[Top-Level architecture]

== Anwendungsfälle

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt
=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Name |Beschreibung |
|…    |…            |
|===

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

== Anforderungen

=== Muss-Kriterien
Was das zu erstellende Programm auf alle Fälle leisten muss.

=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

== GUI Prototyp

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird. Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Aktzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch erfüllt. Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden. D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (welches ein Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft  zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
