= Pflichtenheft

== Projektname

__Version:__    *1.0*

__Status:__     *In Arbeit*

__Stand:__      *29.10.2016*

== Zusammenfassung
Das Pflichtenheft enthält die Aufgabe und Wünsche des Kunden an die zu entwickelnde Software. 

== Inhaltsverzeichnis

== Aufgabenstellung und Zielsetzung

=== Pizzaservice

Der Pizza-Service Papa Pizza liefert Pizzas und Getränke an seine Kunden auf telefonische +
Bestellung frei Haus. Da man bei Papa Pizza schlechte Erfahrungen mit "Telefonscherzen" +
gemacht hat, laufen die Bestellungen wie folgt:  	

* Neue Kunden tätigen ihre erste Bestellung persönlich in der Papa Pizza-Filiale. Dabei +
werden die Kundendaten nebst Telefonnummer aufgenommen. Mit der Rechnung +
erhält der Kunde seine erste TAN (Transaktionsnummer). 

* Im Regelfall bestellen Kunden telefonisch und weisen sich dabei mit ihrer +
Telefonnummer und TAN aus. Damit ist die TAN für den Kunden "verbraucht".

* Bei Auslieferung erhalten Kunden mit der Rechnung eine neue TAN.

* Wer seine Pizza persönlich abholt, erhält einen Rabatt von 10%.

Die Kunden können sich ihre Pizzas aus dem reichhaltigen Angebot an Zutaten individuell +
zusammenstellen. Getränke und Salate werden bei Papa Pizza natürlich ebenfalls angeboten. +
Bei einem Bestellwert von über 30 EUR erhält der Kunde ein Gratisgetränk. +
Pizzas werden in den verfügbaren Öfen im 5-Minuten-Takt gebacken, d.h. alle 5 Minuten +
kann eine weitere Pizza in einen der Öfen geschoben werden. Da die Anzahl der benötigten +
Öfen und Pizzabäcker vom Kundenandrang abhängt, wird sie vierteljährlich an die aktuellen +
Bestellungszahlen angepasst. +
Bei Annahme einer Bestellung wird diese zum nächstmöglichen Zeitpunkt eingeplant und +
dem Kunden der voraussichtliche Lieferzeitraum genannt. Die Lieferboten fahren +
viertelstündlich die Pizzas der vorangegangenen drei Back-Takte (natürlich in + 
Warmhaltebehältnissen) aus. +
Bei Bedarf wird eine Pizza gegen eine Kaution von 15 EUR mit der beliebten Papa Pizza- +
Essgarnitur (Becher, Riesenteller, Besteck) geliefert. Die Garnituren können innerhalb von +
vier Wochen in der Filiale oder beim Auslieferer zurückgegeben werden. Ansonsten verfällt +
die Kaution und gilt als Kaufpreis. +
Von Ihrer Software erwartet Papa Pizza eine angemessene Unterstützung aller Vorgänge +
einschließlich der Pflege des Kundenstamms (mit TAN-Verwaltung), des Personalstammes + 
und des laufenden Sortiments (dessen Zusammenstellung und Preise sich kontinuierlich +
ändern) sowie der wöchentlichen Abrechnungen der Filialen mit der Zentrale. 

== Fachlicher Überblick
Einleitung für fachfremde Personen

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm

link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/artefacts/component__Kontextdiagramm.jpg[Kontextdiagramm]

=== Top-level architecture

link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/artefacts/component__Top_Level_Architektur.jpg[Top-Level architecture]

== Anwendungsfälle

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/artefacts/Use_Case_Diagram_Master.jpg[Use-Case-Diagramm]

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Name |Beschreibung 
|...   |...       
|===

=== Anwendungsfallbeschreibungen
Name des Anwendungsfalls: Zusammenstellung des Warenkorbs auf der Pizzaserviceswebsite +
beteiligte Akteure:  Kunde(Customer) +
Beschreibung: +
Jeder Kunde(Customer) kann ohne sich anzumelden das Angebot des Pizzaservices auf der Website ansehen (browse items/menus). Der Kunde hat die Möglichkeit sich die einzelnen Waren sortiert anzeigen zu lassen und seinem Warenkorb hinzuzufügen (select item/menu).
Ebenfalls besteht dem Kunden die Möglichkeit sich seine Pizza komplett selbst zu konfigurieren (configure pizza). Alle vom Kunden  ausgewählten Waren werden ihm in seinem Warenkorb angezeigt.


Name des Anwendungsfalls: Bestellung eines Kunden entgegennehmen +
beteiligte Akteure:  Verkäufer(Seller), Kunde(Customer) +
Beschreibung: +
Der Kunde gibt telefonisch eine Bestellung auf und muss sich mit seiner Telefonnummer und aktuellen TAN ausweisen. Der Verkäufer trägt die Informationen in das System ein, woraufhin diese mit den Informationen in der Datenbank abgeglichen werden. Sollten diese nicht übereinstimmen, wird der Bestellvorgang abgebrochen. Wenn die Daten übereinstimmen überträgt der Verkäufer die geforderten Waren des Kunden in ein Formular und durch bestätigen wird diese dann in Auftrag gegeben. Die Gesamtkosten der Waren werden ermittelt und für die Abrechnung als Kosten hinzugefügt. (add to expenditure) Ebenfalls wird einen neue TAN für den Kunden generiert, welche in der Kundendatenbank gespeichert wird.

Varianten: +
- Kunde ist noch nicht registriert und möchte sich registrieren
Der Verkäufer startet den Prozess der Registrierung eines neuen Kunden dafür trägt er die Daten des Kunden in ein bereitgestelltes Formular ein und registriert diesen somit im System. Danach nimmt der Verkäufer die Bestellung des Kunden auf. +
- Kunde ist nicht registriert und möchte nur eine einmalige Bestellung ohne Registrierung aufgeben
Der Verkäufer nimmt die Bestellung des Kunden normal entgegen ohne das sich dieser dafür mit seiner TAN ausweisen muss. Nach Abschluss der Bestellung erhält der Kunde dementsprechend auch keine neue TAN.


Name des Anwendungsfalls: Bestellungen bearbeiten +
beteiligte Akteure:  Pizzabäcker(Baker) +
Beschreibung: +
Der Pizzabäcker kann sich im System eine Liste der noch zu backenden Pizzen anzeigen lassen. Diese Pizzen kann er dann einem noch nicht belegten Ofen zuweisen, woraufhin ein 5-Minuten-Timer gestartet wird. Nach Ablauf dieses Timers wird der Pizzabäcker benachrichtigt und die Pizza im System als gebacken markiert.

Name des Anwendungsfalls: Bestellungen ausliefern +
beteiligte Akteure:  Auslieferer(Delivery), Verkäufer(Seller) +
Beschreibung: +
Der Verkäufer hat eine Übersicht über alle fertiggestellten Bestellungen und kann diese dann einem Auslieferer zuweisen, sollten dessen Kapazitäten ausreichen. Wenn einem Auslieferer genügend Bestellungen zugewiesen wurden kann dieser auf den Weg machen und sich dabei vom System abmelden. Ihm können dadurch keine weiteren Bestellungen zugewiesen werden. Wenn er von der Auslieferung zurückgekehrt ist, kann er sich wieder im System anmelden und den vom Kunden erhaltenen Geldbetrag abliefern, welcher dann für die Abrechnung als Einnahmen gespeichert wird.


Name des Anwendungsfalls: Abrechnung erstellen +
beteiligte Akteure:  Administrator +
Beschreibung: +
Der Administrator kann die wöchentliche Abrechnung in Auftrag geben. Dabei werden alle gespeicherten Ausgaben und Einnahmen gegenübergestellt und eine Gesamtbilanz berechnet, die dann an die Zentrale geschickt werden kann

Name des Anwendungsfalls: Datensätze editieren +
beteiligte Akteure:  Administrator +
Beschreibung: +
Der Administrator kann die einzelnen Einträge editieren, sowie neue Einträge hinzufügen, oder bereits bestehende Einträge wieder entfernen

Varianten: +
- Bearbeiten der Kundendatenbank (Customer Database) +
- Bearbeiten der Mitarbeiterdatenbank (Employee Database) +
- Bearbeiten der Warendatenbank (Item Manager) +

== Anforderungen

=== Muss-Kriterien

Was das zu erstellende Programm auf alle Fälle leisten muss.

* Bestellung registrieren
* Kundenverwaltung
* TAN-Verwaltung
* Rabattaktionen
* Pizzen selbst zusammenstellen
* Angebotsverwaltung
* Berechnung der Lieferzeit
* Pizza-Essgarnitur Verwaltung
* Veränderliches Sortiment
* Wöchentliche Abrechnung der Filiale

=== Kann-Kriterien

Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

* Katalog kann Bilder enthalten
* Standortberücksichtigung
* Online-Bestellung per Kundenaccount

== GUI Prototyp

== GUI Prototyp

=== Überblick: Dialoglandkarte
Das Diagram beschreibt den Navigationsfluss der Schlüsselkomponenten der Website und des damit verbunden backends.Seiten von ähnlicher und/oder trivialer Natur wurden bewusst ausgelassen.

*Legende*

* Knotenpunkte: Repräsentieren einzelne Schlüsselstellen im GUI welche den Dialog beschreiben. Die Dialogbeschreibung wird hauptsächlich durch die Konzeptbilder zusammen mit den Notizen in dem Flowchart ausgedrückt. Diese Konzeptentwürfe der Schlüsselstellen liegen als .jpg bei. (Siehe Dialogbeschreibung)
 
 * Pfeile: Beschreiben Flussrichtung, bzw. wie der Benutzer durch die einzelnen Oberflächen navigiert.
 
 * Pfeilannotation: Machen deutlich was ge-clickt werden muss um von einem Bereich in den nächsten zu gelangen.
 
 * Notizen: Gehen auf die Nutzung und den Zweck der einzelnen Komponenten ein.
 
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/GUI_Flowchart.jpg[GUI Flowchart]

=== Dialogbeschreibung
index: 
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/index.jpg[Index]


=== Kunde
pizza_auswahl:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Kunde/pizza_auswahl.jpg[Pizza Auswahl]

pizza_konfigurator:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Kunde/pizza_konfigurator.jpg[Pizza Konfirgurator]

=== Administrator
admin_dashboard:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Administrator/admin_dashboard.jpg[Admin Dashboard]

admin_finanzen:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Administrator/admin_finanzen.jpg[Admin Finanzen]

admin_mitarbeiterübersicht:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Administrator/admin_mitarbeiterübersicht.jpg[Mitarbeiterübersicht]

=== Verkäufer

verkäufer_dashboard:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Verkäufer/verkäufer_dashboard.jpg[Verkäufer Dashboard]

verkäufer_kunden_registrierung:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Verkäufer/verkäufer_kunden_registrierung.jpg[Verkäufer Kundenregistrierung]

verkäufer_produkt_auswahl:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Verkäufer/verkäufer_produkt_auswahl.jpg[Verkäufer Produktauswahl]

=== Adminstrator/Verkäufer/Bäcker/Lieferant

bestellungs_übersicht:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Shared/bestellungs_übersicht.jpg[Bestellungs Übersicht]

kunden_übersicht:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Shared/kunden_übersicht.jpg[Kunden Übersicht]

mitarbeiter_login:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Shared/mitarbeiter_login.jpg[Mitarbeiter Login]

ofen_übersicht:
link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/prototypes/GUI/index/Shared/ofen_übersicht.jpg[Ofen Übersicht]

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

link:https://github.com/st-tu-dresden-praktikum/swt16w16/blob/master/artefacts/Klassendiagramm.jpg[Analyseklassendiagramm]

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Aktzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch erfüllt. Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden. D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (welches ein Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

|=======================
|id|Beschreibung      
|1    | Der Kunde kann aus Waren auswählen und sie dem Warenkorb hinzufügen 		
|2    | Der Mitarbeiter(Admin/Boss,Verkäufer,Bäcker,Lieferant) können sich einloggen und ausloggen      
|3    | Der Verkäufer kann Warenkorb bearbeiten (hinzufügen/entfernen von Waren) und 
		diesen dann in Auftrag geben
|5    | Der Verkäufer ist in der Lage Kunden hinzuzufügen und die TAN von vorhandenen Kunden zu überprüfen
|5    | Der Verkäufer kann Essgarnituren entgegen nehmen und dem Kunden die 15 € aushändigen
|6    | Der Bäcker sieht die Öfen und ihre Timer(max. 5 Minuten), sowie die aktuell benötigten Pizzen und kann Öfen befüllen
|7    | Der Lieferant kann sich ein- und auschecken
|8    | Der Lieferant kann beim einchecken Essgarnituren zurückgeben
|9    | Der Admin sieht die aktuellen Bestellungen (in Form einer Tabelle)
|10    | Der Admin kann den Warenkatalog verändern (Waren ergänzen, löschen sowie von vorhanden den Preis ändern)
|11   | Der Admin hat Zugriff auf die Liste der Mitarbeiter diese verändern (erweitern sowie kürzen)
|12   | Der Admin besitzt die Möglichkeit die Informationen der einzelnen Mitarbeiter zu ändern
|13   | Der Admin hat Einsicht auf die Liste der Kunden und darf einzelne Nutzer bearbeiten sowie entfernen
|14   | Der Admin kann sieht anhand einer Tabelle die Abrechnung der letzten Wochen
|15   | Nach einer Bestellung wird dem Kunden eine neue TAN zugewiesen 
|16   | Wenn der Kunde seine Bestellung vor Ort abholt, erhält er 10% Rabatt auf den Gesamtpreis
|17   | Ab einem Warenwert von 30€ gibt es die Option eines Freigetränkes
|18   | Bei dem Bestellen einer Essgarnitur wird 15 € Pfand verlangt
|19   | Bei Rückgabe der Essgarnitur wird dieser dem Kunden wieder ausgehändigt
|20   | Nach 4 Wochen verfällt der Pfand und die Garnitur zählt als gekauft
|=======================

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft  zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
