= Cross-Testing Feedback

__Durchführende Gruppe: swt16w16__
__Anwendung von Gruppe: swt16w30__

== Getestetes System
//Welche Aufgabe/Problemstellung löst die Anwendung.
=== Erfüllte Muss-Kriterien
* Artikel können vom Admin hinzugefügt werden (bei richtigen Eingaben)
* Artikel können gelöscht werden (wenn keine DIY-Pizza)
* Getrennte  views zwischen Kunden und Mitarbeiter sind vorhanden. Die bereitgestellten Funktionalitäten für die Mitarbeiter sind gegenüber dem Admin limitiert, und sind von dem Kunden nicht einzusehen.

== Fehler-Report
// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Pfad |Parameter |Beschreibung |Rückgabe
| ../ingridients/addNew oder ../simpleProduct/addNew | ""(Name) oder ""als Preis | fehlerhafte Eingaben werden nicht abgefangen  | Weiterleitung zu WhitelabelError("empty String") 
| ../pizza/delete/CustomPizza | --- | Pizza kann nicht gelöscht werden | WhiteLabelError("no message available") 
| ../pizza/delete/CustomPizza | --- | Die Links unter „Unser Angebot“ führen zu einer „Whitelabel Error Page“ und einem 404 Server Fehler. Aufgrund dieses Verhaltens kann der Kunden nicht das komplette(bzw kein)Angebot wahrnehmen.
(Das gleiche Gilt für die Pfade: „customerSalads?“, „customerDrinks?“, 
„customerIngredients?“,„customerPasta?“)
 | WhiteLabelError("no message available") 
|===

== Sonstiges
* Wenn eine Zutat gelöscht wird, kann sie immernoch auf Pizzen zu finden sein
* Artikel können nicht bearbeitet werden
* Essgarniturverleih fehlt komplett
* Liefergebiet ist nicht beschränkt (PLZ von Orten außerhalb von Dresden werden bei einer Bestellung akzeptiert)
* Freigetränk bei einer Bestellung über 30€ fehlt ebenfalls 
* runde Artikelpreise wie z.B. 2€ werden zu 1,99€ gemacht (witzig aber eig. vom Kunden nicht explizit gefordert)
* Es ist nicht möglich eine eine druckbare Version der abgeschlossenen Bestellung zu generieren/drucken

* Optik der Anwendung
* Fehlende Features
* Interaktion mit der Anwendung (Usability)

== Verbesserungsvorschläge
* bessere Fehlerbehandlung (WhiteLabelError umgehen z.b. per "redirect:catalog")
* Was kann noch weiter verbessert werden?
* Die Bausteine für eine druckbare Rechnung sind schon in der Bestellungsübersicht vorhanden, und müssen nur richtig formatiert werden.
